// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUkjUGuxhiv41ozOR8PAutBmnq_UHLMnc',
    appId: '1:202361448439:android:87823d5b63be4e87e530f2',
    messagingSenderId: '202361448439',
    projectId: 'ilemo-app',
    storageBucket: 'ilemo-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFalNyJ5dodorVttd1TNNGrTlVg61_vu8',
    appId: '1:202361448439:ios:797ef6e397b93e0de530f2',
    messagingSenderId: '202361448439',
    projectId: 'ilemo-app',
    storageBucket: 'ilemo-app.firebasestorage.app',
    iosBundleId: 'com.example.ilemo',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzX38JEjMCWy0kItrFsBhz2eoFz57wzp0',
    appId: '1:202361448439:web:6b40d6d0e155e0bfe530f2',
    messagingSenderId: '202361448439',
    projectId: 'ilemo-app',
    authDomain: 'ilemo-app.firebaseapp.com',
    storageBucket: 'ilemo-app.firebasestorage.app',
  );
}
